<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChiefSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('chiefs')->insert([
            [
                'district' => 'Manicaland',
                'province' => 'Buhera',
                'chieftainship' => 'Nyashanu',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'idnumber' => '1',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'numberofvillages'=>'576',
                'contactnumber' => '077777777',
                'numberofheadman' => '12',
                'numberofwards' => '19',
                'physicalladdress' => 'Address',
                'slug' => 'Nyashanu',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
            [
                'district' => 'Manicaland',
                'province' => 'Buhera',
                'chieftainship' => 'Makumbe',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'idnumber' => '2',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'numberofvillages'=>'576',
                'contactnumber' => '077777777',
                'numberofheadman' => '4',
                'numberofwards' => '7',
                'physicalladdress' => 'Address',
                'slug' => 'Makumbe',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
            [
                'district' => 'Manicaland',
                'province' => 'Buhera',
                'chieftainship' => 'Nerutanga',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'idnumber' => '3',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'numberofvillages'=>'576',
                'contactnumber' => '077777777',
                'numberofheadman' => '4',
                'numberofwards' => '1',
                'physicalladdress' => 'Address',
                'slug' => 'Nerutanga',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
            [
                'district' => 'Manicaland',
                'province' => 'Buhera',
                'chieftainship' => 'Chitauro',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'idnumber' => '4',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'numberofvillages'=>'576',
                'contactnumber' => '077777777',
                'numberofheadman' => '0',
                'numberofwards' => '1',
                'physicalladdress' => 'Address',
                'slug' => 'Chitauro',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
            [
                'district' => 'Manicaland',
                'province' => 'Buhera',
                'chieftainship' => 'Gweu',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'idnumber' => '5',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'numberofvillages'=>'576',
                'contactnumber' => '077777777',
                'numberofheadman' => '12',
                'numberofwards' => '19',
                'physicalladdress' => 'Address',
                'slug' => 'Gweu',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
            [
                'district' => 'Manicaland',
                'province' => 'Buhera',
                'chieftainship' => 'Chimombe',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'idnumber' => '6',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'numberofvillages'=>'576',
                'contactnumber' => '077777777',
                'numberofheadman' => '12',
                'numberofwards' => '19',
                'physicalladdress' => 'Address',
                'slug' => 'Chimombe',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
             [
                'district' => 'Manicaland',
                'province' => 'Buhera',
                'chieftainship' => 'Chitsunge',
                'slug' => 'Chitsunge',
                'numberofheadman' => '12',
                'numberofwards' => '19',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'idnumber' => '7',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'numberofvillages'=>'576',
                'contactnumber' => '077777777',
                'physicalladdress' => 'Address',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
            [
                'district' => 'Manicaland',
                'province' => 'Buhera',
                'chieftainship' => 'Chamutsa',
                'slug' => 'Chamutsa',
                'numberofheadman' => '0',
                'numberofwards' => '3',
                'idnumber' => '8',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'numberofvillages'=>'576',
                'contactnumber' => '077777777',
                'physicalladdress' => 'Address',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
             [
                'district' => 'Manicaland',
                'province' => 'Chimanimani',
                'chieftainship' => 'Chikukwa',
                'slug' => 'Chikukwa',
                'numberofheadman' => '0',
                'numberofwards' => '3',
                'idnumber' => '9',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'numberofvillages'=>'576',
                'contactnumber' => '077777777',
                'physicalladdress' => 'Address',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
             [
                'district' => 'Manicaland',
                'province' => 'Chimanimani',
                'chieftainship' => 'Ndimi',
                'slug' => 'Ndimi',
                'numberofheadman' => '0',
                'numberofwards' => '3',
                'idnumber' => '10',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'numberofvillages'=>'576',
                'contactnumber' => '077777777',
                'physicalladdress' => 'Address',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
             [
                'district' => 'Manicaland',
                'province' => 'Chimanimani',
                'chieftainship' => 'Ngorima',
                'slug' => 'Ngorima',
                'numberofheadman' => '0',
                'numberofwards' => '3',
                'idnumber' => '11',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'numberofvillages'=>'576',
                'contactnumber' => '077777777',
                'physicalladdress' => 'Address',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
             [
                'district' => 'Manicaland',
                'province' => 'Chimanimani',
                'chieftainship' => 'Mutambara',
                'slug' => 'Mutambara',
                'numberofheadman' => '0',
                'numberofwards' => '3',
                'idnumber' => '14',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'numberofvillages'=>'576',
                'contactnumber' => '077777777',
                'physicalladdress' => 'Address',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
             [
                'district' => 'Manicaland',
                'province' => 'Chimanimani',
                'chieftainship' => 'Muusha',
                'slug' => 'Muusha',
                'numberofheadman' => '0',
                'numberofwards' => '3',
                'idnumber' => '15',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'numberofvillages'=>'576',
                'contactnumber' => '077777777',
                'physicalladdress' => 'Address',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
             [
                'district' => 'Manicaland',
                'province' => 'Chimanimani',
                'chieftainship' => 'Sourumba',
                'slug' => 'Sourumba',
                'numberofheadman' => '0',
                'numberofwards' => '3',
                'idnumber' => '16',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'numberofvillages'=>'576',
                'contactnumber' => '077777777',
                'physicalladdress' => 'Address',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
      ]);

    }
}
