<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class HeadmanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('headmans')->insert([
             [
                'district' => 'Manicaland',
                'province' => 'Buhera',
                'chieftainship' => 'Nyashanu',
                'headmanship'=>'Nemhari',
                'numberofvillages'=>'42',
                'numberofhousehold'=>'2591',
                'slug' => 'Nemhari',
                'numberofwards' => '2',
                'idnumber' => '1',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'numberofvillages'=>'576',
                'contactnumber' => '077777777',
                'physicalladdress' => 'Address',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
              [
                'district' => 'Manicaland',
                'province' => 'Buhera',
                'chieftainship' => 'Nyashanu',
                'headmanship'=>'Neshava',
                'numberofvillages'=>'35',
                'numberofhousehold'=>'2019',
                'slug' => 'Nyashanu',
                'numberofwards' => '1',
                'idnumber' => '2',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'contactnumber' => '077777777',
                'physicalladdress' => 'Address',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
             [
                'district' => 'Manicaland',
                'province' => 'Buhera',
                'chieftainship' => 'Nyashanu',
                'headmanship'=>'Murambinda',
                'numberofvillages'=>'41',
                'numberofhousehold'=>'2710',
                'slug' => 'Murambinda',
                'numberofwards' => '1',
                'idnumber' => '3',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'contactnumber' => '077777777',
                'physicalladdress' => 'Address',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
            [
                'district' => 'Manicaland',
                'province' => 'Buhera',
                'chieftainship' => 'Nyashanu',
                'headmanship'=>'Mudinzwa',
                'numberofvillages'=>'41',
                'numberofhousehold'=>'2710',
                'slug' => 'Mudinzwa',
                'numberofwards' => '1',
                'idnumber' => '5',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'contactnumber' => '077777777',
                'physicalladdress' => 'Address',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
             [
                'district' => 'Manicaland',
                'province' => 'Buhera',
                'chieftainship' => 'Nyashanu',
                'headmanship'=>'Nechavava',
                'numberofvillages'=>'45',
                'numberofhousehold'=>'2510',
                'slug' => 'Nechavava',
                'numberofwards' => '1',
                'idnumber' => '6',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'contactnumber' => '077777777',
                'physicalladdress' => 'Address',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
             [
                'district' => 'Manicaland',
                'province' => 'Buhera',
                'chieftainship' => 'Nyashanu',
                'headmanship'=>'Mabvuregudo',
                'numberofvillages'=>'41',
                'numberofhousehold'=>'2710',
                'slug' => 'Mabvuregudo',
                'numberofwards' => '1',
                'idnumber' => '8',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'contactnumber' => '077777777',
                'physicalladdress' => 'Address',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
             [
                'district' => 'Manicaland',
                'province' => 'Buhera',
                'chieftainship' => 'Nyashanu',
                'headmanship'=>'Bangure',
                'numberofvillages'=>'41',
                'numberofhousehold'=>'2710',
                'slug' => 'Bangure',
                'numberofwards' => '1',
                'idnumber' => '9',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'contactnumber' => '077777777',
                'physicalladdress' => 'Address',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
             [
                'district' => 'Manicaland',
                'province' => 'Buhera',
                'chieftainship' => 'Nyashanu',
                'headmanship'=>'Murwira',
                'numberofvillages'=>'41',
                'numberofhousehold'=>'2710',
                'slug' => 'Murwira',
                'numberofwards' => '1',
                'idnumber' => '10',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'contactnumber' => '077777777',
                'physicalladdress' => 'Address',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
             [
                'district' => 'Manicaland',
                'province' => 'Buhera',
                'chieftainship' => 'Nyashanu',
                'headmanship'=>'Mawire',
                'numberofvillages'=>'41',
                'numberofhousehold'=>'2710',
                'slug' => 'Mawire',
                'numberofwards' => '1',
                'idnumber' => '11',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'contactnumber' => '077777777',
                'physicalladdress' => 'Address',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
             [
                'district' => 'Manicaland',
                'province' => 'Buhera',
                'chieftainship' => 'Nyashanu',
                'headmanship'=>'Chirozva',
                'numberofvillages'=>'41',
                'numberofhousehold'=>'2710',
                'slug' => 'Chirozva',
                'numberofwards' => '1',
                'idnumber' => '12',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'contactnumber' => '077777777',
                'physicalladdress' => 'Address',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
             [
                'district' => 'Manicaland',
                'province' => 'Buhera',
                'chieftainship' => 'Nyashanu',
                'headmanship'=>'Mushumba',
                'numberofvillages'=>'41',
                'numberofhousehold'=>'2710',
                'slug' => 'Mushumba',
                'numberofwards' => '1',
                'idnumber' => '13',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'contactnumber' => '077777777',
                'physicalladdress' => 'Address',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
             [
                'district' => 'Manicaland',
                'province' => 'Buhera',
                'chieftainship' => 'Nyashanu',
                'headmanship'=>'Chimombe',
                'numberofvillages'=>'41',
                'numberofhousehold'=>'2710',
                'slug' => 'Chimombe',
                'numberofwards' => '1',
                'idnumber' => '142',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'contactnumber' => '077777777',
                'physicalladdress' => 'Address',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
             [
                'district' => 'Manicaland',
                'province' => 'Buhera',
                'chieftainship' => 'Nyashanu',
                'headmanship'=>'Mufudza',
                'numberofvillages'=>'41',
                'numberofhousehold'=>'2710',
                'slug' => 'Mufudza',
                'numberofwards' => '1',
                'idnumber' => '14',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'contactnumber' => '077777777',
                'physicalladdress' => 'Address',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
             [
                'district' => 'Manicaland',
                'province' => 'Buhera',
                'chieftainship' => 'Makumbe',
                'headmanship'=>'Chapwanya',
                'numberofvillages'=>'41',
                'numberofhousehold'=>'2710',
                'slug' => 'Chapwanya',
                'numberofwards' => '1',
                'idnumber' => '15',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'contactnumber' => '077777777',
                'physicalladdress' => 'Address',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
            [
                'district' => 'Manicaland',
                'province' => 'Buhera',
                'chieftainship' => 'Makumbe',
                'headmanship'=>'Mbundire',
                'numberofvillages'=>'41',
                'numberofhousehold'=>'2710',
                'slug' => 'Mbundire',
                'numberofwards' => '1',
                'idnumber' => '16',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'contactnumber' => '077777777',
                'physicalladdress' => 'Address',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
            [
                'district' => 'Manicaland',
                'province' => 'Buhera',
                'chieftainship' => 'Makumbe',
                'headmanship'=>'Mudzamire',
                'numberofvillages'=>'41',
                'numberofhousehold'=>'2710',
                'slug' => 'Mudzamire',
                'numberofwards' => '1',
                'idnumber' => '17',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'contactnumber' => '077777777',
                'physicalladdress' => 'Address',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
            [
                'district' => 'Manicaland',
                'province' => 'Buhera',
                'chieftainship' => 'Makumbe',
                'headmanship'=>'Murume',
                'numberofvillages'=>'41',
                'numberofhousehold'=>'2710',
                'slug' => 'Murume',
                'numberofwards' => '1',
                'idnumber' => '18',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'contactnumber' => '077777777',
                'physicalladdress' => 'Address',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],
            [
                'district' => 'Manicaland',
                'province' => 'Buhera',
                'chieftainship' => 'Makumbe=',
                'headmanship'=>'Masveru',
                'numberofvillages'=>'41',
                'numberofhousehold'=>'2710',
                'slug' => 'Masveru',
                'numberofwards' => '1',
                'idnumber' => '19',
                'mutupo' => 'Mutupo',
                'incumbent' => 'Incumbent',
                'ecnumber' => 'Ecnumber',
                'gender' => 'male',
                'dateofappointment' => '2022-12-14',
                'dateofbirth' => '2022-12-14',
                'status' => 'status',
                'contactnumber' => '077777777',
                'physicalladdress' => 'Address',
                'created_at' => '2022-12-06 11:32:28',
                'updated_at' => '2022-12-06 11:32:28',
            ],

        ]);
    }
}
